In [64]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
from shutil import copyfile

%matplotlib inline

classes={0:'airplane',
1:'automobile',
2:'bird',
3:'cat',
4:'deer',
5:'dog',
6:'frog',
7:'horse',
8:'ship',
9:'truck'}

In [88]:

mod_lab=np.loadtxt('perturbed_data/new_labels')
mod_con=np.loadtxt('perturbed_data/new_confidences')
ori_lab=np.loadtxt('perturbed_data/labels')
ori_con=np.loadtxt('perturbed_data/confidences')

In [96]:

(mod_lab==ori_lab).sum()
np.median(mod_con)
(mod_con>0.99).sum()
good=(mod_con>0.99) & (ori_con>0.50)
good.sum()
np.unique(ori_lab[good])
# np.unique(mod_lab[good])
#ori_lab[good]
good_idx=np.where(good)[0]

In [119]:
#!mkdir selected_imgs
final_idx=np.zeros(20, dtype=int)
for label in range(10):
    idx=(ori_lab[good]==label)
#     print(idx)
    if idx.sum()<2: raise Exception('not enough images for this label')
    idx=np.where(idx)[0]
#     print(idx)
    con_sort=np.flip(ori_con[good_idx[idx]].argsort(),axis=0)
    idx=idx[con_sort]
#     print(idx)
    for i in range(2):
        copyfile('perturbed_imgs/'+str(good_idx[idx[i]])+'_modified.png', 
                  'selected_imgs/'+str(2*label+(i))+'_modified.png')
        copyfile('perturbed_imgs/'+str(good_idx[idx[i]])+'_original.png',
                  'selected_imgs/'+str(2*label+(i))+'_original.png')
        final_idx[2*label+(i)]=good_idx[idx[i]]

In [122]:
print(ori_lab[final_idx])
print(mod_lab[final_idx])
print(ori_con[final_idx])
print(mod_con[final_idx])
classes={0:'airplane',
1:'automobile',
2:'bird',
3:'cat',
4:'deer',
5:'dog',
6:'frog',
7:'horse',
8:'ship',
9:'truck'}
for i in range(20):
    print(classes[mod_lab[final_idx][i]])
    #print(classes[ori_lab[final_idx][i]])

[ 0.  0.  1.  1.  2.  2.  3.  3.  4.  4.  5.  5.  6.  6.  7.  7.  8.  8.
  9.  9.]
[ 8.  8.  8.  9.  4.  0.  7.  7.  7.  7.  7.  6.  4.  9.  9.  9.  9.  9.
  8.  1.]
[ 0.99925941  0.99603707  0.99713081  0.99522543  0.94232315  0.87075555
  0.91071475  0.88711876  0.96952224  0.94690043  0.79756457  0.79297543
  0.99810398  0.99293488  0.99429542  0.97991848  0.99927574  0.99706393
  0.97863436  0.97782862]
[ 0.99566841  0.99599373  0.99153674  0.99549663  0.99134821  0.99444526
  0.99926406  0.99212354  0.99501234  0.99708849  0.99476308  0.99470574
  0.99305832  0.99318552  0.99536717  0.99888498  0.99949837  0.9972856
  0.99478167  0.99547172]
ship
ship
ship
truck
deer
airplane
horse
horse
horse
horse
horse
frog
deer
truck
truck
truck
truck
truck
ship
automobile


In [34]:
idx=ori_lab[good]==0
np.where(idx)   

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]),)

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9])

In [82]:
np.flip(np.array([1,2,3,4]).argsort(),axis=0)

array([3, 2, 1, 0])